sets = [
	'Eighth Edition',
	'Ninth Edition',
	'Tenth Edition',
	'Onslaught',
	'Legions',
	'Scourge',
	'Mirrodin',
	'Darksteel',
	'Fifth Dawn',
	'Champions of Kamigawa',
	'Betrayers of Kamigawa',
	'Saviors of Kamigawa',
	'Ravnica: City of Guilds',
	'Guildpact',
	'Dissension',
	'Coldsnap',
	'Time Spiral',
	'Planar Chaos',
	'Future Sight',
	'Lorwyn',
	'Morningtide',
	'Shadowmoor',
	'Eventide',
	'Shards of Alara',
	'Conflux',
	'Alara Reborn',
	'Magic 2010',
	'Zendikar',
	'Worldwake'
]
sets.reverse()